palette = "catppuccin_mocha"
right_format = "$time"

[aws]
symbol = "  "

[dart]
symbol = " "

[directory]
style = 'bold sapphire'
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
style = 'bold flamingo'
symbol = " "

[git_metrics]
disabled = false
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed maroon'
format = '\[([+$added]($added_style) )([-$deleted]($deleted_style))\] '

[git_state]
disabled = true

[git_status]
disabled = true

[golang]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[time]
disabled = false
format = "[$time]($style)"
style = "dimmed white"

[zig]
symbol = " "

[gradle]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
